# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "630b08e4dfd9941dd4e7e07a234b676e"
name = "mobile-app-connector"
handle = "mobile-app-connector"
application_url = "https://wheat-utils-negotiations-madagascar.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://wheat-utils-negotiations-madagascar.trycloudflare.com/auth/callback",
  "https://wheat-utils-negotiations-madagascar.trycloudflare.com/auth/shopify/callback",
  "https://wheat-utils-negotiations-madagascar.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
